config/routes.rb
CouponsCode::Engine.routes.draw do
  resources :coupons
  root to: "coupons#index"
end

app/models/coupons_code/coupon.rb
module CouponsCode
  class Coupon < ActiveRecord::Base
  	 # Set table name.
      self.table_name = :coupons

      #before_save :set_name
      has_many :redemptions, class_name: 'CouponsCode::CouponRedemption'

      validates_presence_of :code, :valid_from
      validates_uniqueness_of :code
      validates_numericality_of :redemption_limit, greater_than_or_equal_to: 0
      validates_numericality_of :amount,
                    greater_than_or_equal_to: 0,
                    less_than_or_equal_to: 100,
                    only_integer: true, if: Proc.new { self.discount_type == 'percentage'}  
                    
      validates_numericality_of :amount,
                    greater_than_or_equal_to: 0,
                    only_integer: true, if: Proc.new {self.discount_type == 'amount' }
                    
      validate :validate_dates

      def self.apply(options,coupon)
        @coupon = coupon       
        puts input_amount = BigDecimal("#{options[:amount]}")
        puts discount = BigDecimal(percentage_based? ? percentage_discount(options[:amount],@coupon.amount) : @coupon.amount)
        total = [0, input_amount - discount].max        
        options = options.merge(total: total, discount: discount, error: 'success')        
        options
      end

     
      def self.percentage_based?
        @coupon.discount_type == 'percentage'
      end

      def self.amount_based?
        discount_type == 'amount'
      end


      private

        def self.percentage_discount(input_amount,amount)        
        BigDecimal("#{input_amount}") * (BigDecimal("#{amount}") / 100).to_f
        end

        def validate_dates
          if valid_until_before_type_cast.present?
            errors.add(:valid_until, :invalid) unless valid_until.kind_of?(Date)
            errors.add(:valid_until, "must be equal to or greater than today") if valid_until? && valid_until < Date.current
          end

          if valid_from.present? && valid_until.present?
            errors.add(:valid_until, "must be greater than or equal to valid from date.") if valid_until < valid_from
          end
        end

  end
end

app/models/coupons_code/coupon_redemption.rb
module CouponsCode
  class CouponRedemption < ActiveRecord::Base
  	# Set table name.
      self.table_name = :coupon_redemptions
      belongs_to :Coupon, counter_cache: true
  end
end

app/controllers/coupons_code/application_controller.rb
module CouponsCode
  class ApplicationController < ActionController::Base
  end
end

app/controllers/coupons_code/coupons_controller.rb
require_dependency "coupons_code/application_controller"

module CouponsCode
  class CouponsController < ApplicationController
    before_action :set_coupon, only: [:show, :edit, :update, :destroy]

    # GET /coupons
    def index
      @coupons = Coupon.all
    end

    

    # GET /coupons/new
    def new
      @coupon = Coupon.new
    end

    # GET /coupons/1/edit
    def edit
    end

    # POST /coupons
    def create
      @coupon = Coupon.new(coupon_params)     
      if @coupon.save
        redirect_to coupons_path, notice: 'Coupon was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /coupons/1
    def update
      if @coupon.update(coupon_params)
       redirect_to coupons_path, notice: 'Coupon was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /coupons/1
    def destroy
      @coupon.destroy
      redirect_to coupons_url, notice: 'Coupon was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_coupon
        @coupon = Coupon.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def coupon_params
      params.require(:coupon).permit(:code,:description,:valid_from,:valid_until,:amount,:redemption_limit,:discount_type)
      end
  end
end

app/helpers/coupons_code/application_helper.rb
module CouponsCode
  module ApplicationHelper
  	
  end
end

app/helpers/coupons_code/coupons_helper.rb
module CouponsCode
  module CouponsHelper

      def coupon_discount(coupon)       
        return  "#{coupon.amount}% OFF"  if coupon.discount_type == 'percentage'       
        return  "$#{coupon.amount} OFF"       
      end

      def redeemed(coupon)
        limit = coupon.redemption_limit
        return "Not yet" if limit == 0
        return "#{coupon.coupon_redemptions_count} / #{coupon.redemption_limit}" if limit >  0
      end

       def valid_until(coupon)
         if coupon.valid_until?
         short_date(coupon.valid_until)
         else
         "Never"
         end
       end

       def short_date(date)
         date.to_formatted_s(:long)
       end
  end
end

app/views/coupons_code/coupons/_form.html.erb
<div class="panel panel-default">
  <div class="panel-body">
<%= form_for(@coupon) do |f| %>
  <% if @coupon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@coupon.errors.count, "error") %> prohibited this coupon from being saved:</h2>

      <ul>
      <% @coupon.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div class="form-group">
    <%= f.label :code  %><br>
    <%= f.text_field :code ,:class =>"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description,:class =>"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :valid_from %><br>
    <%= f.date_field :valid_from,:class =>"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :valid_until, "Valid until  (When will this coupon expire. By default, it does not expire.)" %><br>
    <%= f.date_field :valid_until,:class =>"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :redemption_limit, "Coupons Limit  (Set how many times this coupon can be used. Zero means no limit.)" %><br>
    <%= f.number_field :redemption_limit,:class =>"form-control" %>
  </div> 
  <div class="form-group">
    <%= f.label :discount_type %><br>
    <%= f.select :discount_type, options_for_select([ ["Percentage",'percentage'],["Amount",'amount']],:selected => @coupon.discount_type),{},:class =>"form-control" %>
  </div>  
  <div class="form-group">
    <%= f.label :amount, "Amount  (This is the actual discount amount. 0-100 for percentage, zero or positive number for amount.)" %><br>
    <%= f.text_field :amount,:class =>"form-control" %>
  </div>  
  
 <div class="form-actions">
    <%= f.submit :class => "btn btn-success"%> <%= link_to 'Back', coupons_path ,:class => "btn btn-danger"%>
  </div>

<% end %>

  </div>
    </div>

app/views/coupons_code/coupons/edit.html.erb
<h1>Editing Coupon</h1>

<%= render 'form' %>

app/views/coupons_code/coupons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Coupons</h1>

<div class="table-responsive">
<table class="table table-hover">  <thead>
  <thead>
    <tr>
      <th>Code</th>
      <th>Discount</th>
      <th>ValidFrom</th>
      <th>ValidUntil</th>      
      <th>Redeemed</th>     
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @coupons.each do |coupon| %>
    <tr>
      <td><%= coupon.code %></td>
      <td><%= coupon_discount(coupon) %></td>
      <td><%= short_date(coupon.valid_from) %></td>
      <td><%= valid_until(coupon) %></td>
      <td><%= redeemed(coupon) %></td>
    
       
        <td> <%= link_to  edit_coupon_path(coupon), class: "btn btn-primary" do %>
              <i class="glyphicon glyphicon-edit"></i>
           <% end %> 
    <%= link_to  coupon,class: "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } do %>
              <i class="glyphicon glyphicon-trash"></i>
           <% end %>       </td>
      </tr>
    <% end %>
  </tbody>
</table>
<div>
<br>
<%= link_to 'Create Coupon', new_coupon_path ,:class => "btn btn-success"%>

    

app/views/coupons_code/coupons/new.html.erb
<h1>New Coupon</h1>

<%= render 'form' %>

app/views/layouts/coupons_code/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CouponsCode</title>
  <%= stylesheet_link_tag    "coupons_code/application", media: "all" %>
  <%= javascript_include_tag "coupons_code/application" %>
  <%= csrf_meta_tags %>
</head>
<body>
 <div class="container">
<%= yield %>
</div>
</body>
</html>